language: scala
sudo: false

scala:
  - 2.12.4

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.coursier

script:
  - sbt ";fmt ;fix ;coverage ;test"

after_success:
  - sbt coverageReport codacyCoverage
  - bash <(curl -s https://codecov.io/bash)
